 CDEBUGFLAGS+=-D_MSX1
 UOBJS+=vm/ay_3_891x.o \
	vm/datarec.o \
	vm/disk.o \
	vm/event.o \
	vm/fmgen/fmgen.o \
	vm/fmgen/fmtimer.o \
	vm/fmgen/opna.o \
	vm/fmgen/psg.o \
	vm/i8255.o \
	vm/io.o \
	vm/msx/joystick.o \
	vm/msx/kanjirom.o \
	vm/msx/keyboard.o \
	vm/msx/memory_ex.o \
	vm/msx/msx_ex.o \
	vm/msx/printer.o \
	vm/msx/scc.o \
	vm/msx/sound_cart.o \
	vm/noise.o \
	vm/not.o \
	vm/pcm1bit.o \
	vm/prnfile.o \
	vm/tms9918a.o \
	vm/ym2413.o \
	vm/z80.o 

TARGET_NAME= emuMSX1