 CDEBUGFLAGS+=-D_HC20
 UOBJS+= vm/beep.o \
	vm/disk.o \
	vm/event.o \
	vm/hc20/hc20.o \
	vm/hc20/memory.o \
	vm/hd146818p.o \
	vm/i8255.o \
	vm/mc6800.o \
	vm/noise.o \
	vm/tf20.o \
	vm/upd765a.o \
	vm/z80.o \
	vm/z80sio.o 

TARGET_NAME= emuHC20