CDEBUGFLAGS+=-D_PASOPIA
UOBJS+=vm/datarec.o \
	vm/disk.o \
	vm/event.o \
	vm/hd46505.o \
	vm/i8255.o \
	vm/io.o \
	vm/ls393.o \
	vm/noise.o \
	vm/not.o \
	vm/pasopia/display.o \
	vm/pasopia/floppy.o \
	vm/pasopia/joypac2.o \
	vm/pasopia/kanjipac2.o \
	vm/pasopia/keyboard.o \
	vm/pasopia/memory.o \
	vm/pasopia/pac2.o \
	vm/pasopia/pasopia.o \
	vm/pasopia/rampac2.o \
	vm/pcm1bit.o \
	vm/upd765a.o \
	vm/z80.o \
	vm/z80ctc.o \
	vm/z80pio.o 

TARGET_NAME= emuPasopia